<Button>
    font_size:32


<MyLayout>
    #canvas.before:
    #    Color:
    #        rgba: (240/255, 230/255, 200/255, 1)
    #    Rectangle:
    #        pos: self.pos
    #        size: self.size

    BoxLayout:
        orientation: "vertical"
        size: root.width, root.height

        padding: 10
        spacing: 10

        Image:
            source: 'img/r7_c.png'
            allow_stretch: True
            keep_ratio: True

        #Button:
            #text: "Submit"
