<MyGridLayout>
    GridLayuot:
        cols: 1

        GridLayout:
            cols: 2

            Label:
                text: "Name"
            TextInput:
                multiline:True

            Label:
                text: "Name"
            TextInput:
                multiline:True

            Label:
                text: "Name"
            TextInput:
                multiline:True



